version: "3"
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - otel-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - otel-network

  # Server
  server:
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=otel-server
      - OTLP_ENDPOINT=jaeger:4317
      - TRACES_ENABLED=true
      - METRICS_ENABLED=true
      - SERVER_PORT=8080
    networks:
      - otel-network
    depends_on:
      - jaeger
      - prometheus

  # Client
  client:
    build:
      context: .
      dockerfile: ./build/client/Dockerfile
    environment:
      - SERVICE_NAME=otel-client
      - OTLP_ENDPOINT=jaeger:4317
      - TRACES_ENABLED=true
      - METRICS_ENABLED=true
      - SERVER_URL=http://server:8080/hello
    networks:
      - otel-network
    depends_on:
      - server
      - jaeger
    restart: on-failure

networks:
  otel-network:
    driver: bridge
