global:
  scrape_interval: 15s

scrape_configs:
  # Server メトリクス
  - job_name: 'otel-server'
    static_configs:
      - targets: ['server:8088']
    
  # Client メトリクス
  - job_name: 'otel-client'
    static_configs:
      - targets: ['client:8088']
    
  # Jaeger メトリクス
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
